#include <furi.h>

#include <gui/gui.h>
#include <gui/view_holder.h>
#include <gui/modules/text_box.h>

#include <api_lock.h>

#include <infrared/worker/infrared_transmit.h>

/* generated by fbt from .png files in images folder */
#include <hisense_ir_icons.h>

// This function will be called when the user presses the Back button.
static void hisense_ir_back_callback(void* context) {
    FuriApiLock exit_lock = context;
    // Unlock the exti lock, thus enabling the app to exit.
    api_lock_unlock(exit_lock);
}

int32_t hisense_ir_app(void* arg) {
    UNUSED(arg);

    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm hisense_ir!");

    // Access the GUI API instance.
    Gui* gui = furi_record_open(RECORD_GUI);
    // Create a TextBox view. The Gui object only accepts
    // ViewPort instances, so we will need to address that later.
    TextBox* text_box = text_box_alloc();
    // Set some text so that the text box is not empty.
    text_box_set_text(
        text_box,
        "ViewHolder is being used\n"
        "to show this TextBox view.\n\n"
        "Scroll down to see more.\n\n\n"
        "Press \"Back\" to exit.");

    // Create a ViewHolder instance. It will serve as an adapter to convert
    // between the View type provided by the TextBox view and the ViewPort type
    // that the GUI can actually display.
    ViewHolder* view_holder = view_holder_alloc();
    // Let the GUI know about this ViewHolder instance.
    view_holder_attach_to_gui(view_holder, gui);
    // Set the view that we want to display.
    view_holder_set_view(view_holder, text_box_get_view(text_box));

    FuriApiLock exit_lock = api_lock_alloc_locked();
    view_holder_set_back_callback(view_holder, hisense_ir_back_callback, exit_lock);



    uint32_t timings[] = {
        8998, // Leading mark: 9ms
        4469, // Leading space: 4.5ms

        // Byte 1: 0xC1
        567, 1703, // 1
        534, 1712, // 1
        535, 565,  // 0
        548, 532,  // 0
        571, 537,  // 0
        566, 545,  // 0
        568, 544,  // 0
        569, 1680, // 1

        // Byte 2: 0x60
        567, 551,  // 0
        541, 1705, // 1
        542, 1708, // 1
        539, 537,  // 0
        576, 536,  // 0
        567, 542,  // 0
        571, 542,  // 0
        571, 531,  // 0

        // Byte 3: 0x00
        572, 521,  // 0
        571, 525,  // 0
        567, 532,  // 0
        571, 533,  // 0
        570, 537,  // 0
        566, 544,  // 0
        569, 544,  // 0
        569, 533,  // 0

        // Byte 4: 0x40
        570, 523,  // 0
        569, 1674, // 1
        563, 537,  // 0
        576, 531,  // 0
        572, 534,  // 0
        569, 541,  // 0
        572, 541,  // 0
        572, 530,  // 0

        // Byte 5: 0x00
        573, 520,  // 0
        572, 524,  // 0
        568, 531,  // 0
        572, 532,  // 0
        571, 536,  // 0
        567, 543,  // 0
        570, 543,  // 0
        570, 532,  // 0

        // Byte 6: 0x00
        571, 522,  // 0
        570, 526,  // 0
        566, 533,  // 0
        570, 534,  // 0
        569, 538,  // 0
        565, 545,  // 0
        568, 545,  // 0
        568, 521,  // 0

        571,

        7965,

        // Byte 7: 0x03
        568, 552,  // 0
        540, 557,  // 0
        546, 533,  // 0
        570, 532,  // 0
        571, 535,  // 0
        568, 542,  // 0
        571, 1690, // 1
        568, 1710, // 1

        // Byte 8: 0x00
        538, 555,  // 0
        548, 528,  // 0
        564, 534,  // 0
        569, 533,  // 0
        570, 537,  // 0
        566, 545,  // 0
        568, 545,  // 0
        568, 534,  // 0

        // Byte 9: 0x00
        569, 524,  // 0
        568, 528,  // 0
        564, 535,  // 0
        568, 535,  // 0
        568, 539,  // 0
        564, 546,  // 0
        567, 546,  // 0
        567, 535,  // 0

        // Byte 10: 0x00
        568, 525,  // 0
        567, 529,  // 0
        563, 536,  // 0
        567, 536,  // 0
        567, 540,  // 0
        563, 547,  // 0
        566, 548,  // 0
        565, 536,  // 0

        // Byte 11: 0x00
        567, 526,  // 0
        566, 530,  // 0
        573, 527,  // 0
        565, 538,  // 0
        565, 542,  // 0
        571, 539,  // 0
        564, 550,  // 0
        563, 538,  // 0

        // Byte 12: 0x00
        565, 528,  // 0
        564, 532,  // 0
        571, 529,  // 0
        563, 540,  // 0
        563, 543,  // 0
        570, 540,  // 0
        573, 541,  // 0
        572, 529,  // 0

        // Byte 13: 0x00
        563, 530,  // 0
        562, 534,  // 0
        569, 531,  // 0
        572, 531,  // 0
        572, 535,  // 0
        568, 542,  // 0
        571, 543,  // 0
        570, 532,  // 0

        // Byte 14: 0x43
        571, 521,  // 0
        571, 1698, // 1
        539, 535,  // 0
        568, 540,  // 0
        563, 541,  // 0
        572, 538,  // 0
        565, 1722, // 1
        536, 1704, // 1

        543,

        7970,

        // Byte 15: 0x00
        563, 557,  // 0
        535, 562,  // 0
        541, 537,  // 0
        566, 537,  // 0
        566, 540,  // 0
        563, 547,  // 0
        566, 548,  // 0
        565, 536,  // 0

        // Byte 16: 0x40
        567, 526,  // 0
        566, 1677, // 1
        570, 530,  // 0
        573, 535,  // 0
        568, 536,  // 0
        567, 544,  // 0
        569, 545,  // 0
        568, 534,  // 0

        // Byte 17: 0x00
        569, 524,  // 0
        568, 527,  // 0
        565, 535,  // 0
        568, 535,  // 0
        568, 539,  // 0
        564, 547,  // 0
        566, 547,  // 0
        566, 536,  // 0

        // Byte 18: 0x00
        567, 526,  // 0
        566, 530,  // 0
        562, 537,  // 0
        566, 537,  // 0
        566, 541,  // 0
        572, 538,  // 0
        565, 549,  // 0
        564, 538,  // 0

        // Byte 19: 0x10
        565, 528,  // 0
        564, 532,  // 0
        571, 528,  // 0
        564, 1712, // 1
        535, 546,  // 0
        567, 548,  // 0
        565, 545,  // 0
        568, 535,  // 0

        // Byte 20: 0x00
        568, 526,  // 0
        566, 529,  // 0
        563, 536,  // 0
        567, 537,  // 0
        566, 541,  // 0
        572, 538,  // 0
        565, 549,  // 0
        564, 537,  // 0

        // Byte 21: 0x50
        566, 527,  // 0
        565, 1704, // 1
        543, 530,  // 0
        573, 1706, // 1
        541, 540,  // 0
        573, 542,  // 0
        571, 539,  // 0
        564, 527,  // 0

        565 // Stop bit: 562.5us
    };

    infrared_send_raw(timings, sizeof(timings) / sizeof(timings[0]), true);

    api_lock_wait_unlock_and_free(exit_lock);

    view_holder_set_view(view_holder, NULL);
    view_holder_free(view_holder);
    text_box_free(text_box);
    furi_record_close(RECORD_GUI);

    return 0;
}
